# Generated by Django 5.0.6 on 2024-07-05 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_clientes/')),
                ('nome', models.CharField(max_length=255)),
                ('rg', models.CharField(max_length=12, unique=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('data_nascimento', models.DateField()),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prazos', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExameMarcado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_exame', models.DateField()),
                ('date_entrega_exame', models.DateField()),
                ('comentarios_resultados', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('documentos_exames', models.FileField(blank=True, null=True, upload_to='documentos_exames/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica_app.cliente')),
                ('exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica_app.exame')),
            ],
        ),
    ]
